# Generated by Django 2.2.1 on 2019-07-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190725_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
